-- AlterTable
ALTER TABLE "titles" ALTER COLUMN "imdb_rating" SET DATA TYPE TEXT,
ALTER COLUMN "imdb_votes" SET DATA TYPE TEXT,
ALTER COLUMN "meta_score" SET DATA TYPE TEXT,
ALTER COLUMN "box_office" DROP NOT NULL,
ALTER COLUMN "production" DROP NOT NULL,
ALTER COLUMN "website" DROP NOT NULL;
